    CREATE TABLE "ZZHA"."EMPLOYEEMR"
   (
    "EID" NUMBER NOT NULL ENABLE,
    "EMAIL" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(64 BYTE) NOT NULL ENABLE,
    "USERTYPE" VARCHAR2(32 BYTE) NOT NULL ENABLE,
    "NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"PHONE" VARCHAR2(20 BYTE),
	"MONTHLY_PAY" NUMBER NOT NULL ENABLE,
	"PAYROLL" VARCHAR2(200 BYTE),
    "START_DATE" DATE,
    PRIMARY KEY ("EID"));

CREATE TABLE "ZZHA"."MECHANIC"
   (
    "EID" NUMBER NOT NULL ENABLE,
    "EMAIL" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(64 BYTE) NOT NULL ENABLE,
    "NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"PHONE" VARCHAR2(20 BYTE),
	"HOUR_WORKED" NUMBER,
	"HOURLY_PAY" NUMBER NOT NULL ENABLE,
	"PAYROLL" VARCHAR2(200 BYTE),
  "START_DATE" DATE,
    PRIMARY KEY ("EID")
    );

CREATE TABLE "ZZHA"."SERVICE_CENTER"
   (
    "SID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(200 BYTE),
	"PHONE" VARCHAR2(20 BYTE),
    PRIMARY KEY ("SID")
    );

CREATE TABLE "ZZHA"."DISTRIBUTOR"
   (
    "DID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
    PRIMARY KEY ("DID")
    );

CREATE TABLE "ZZHA"."EMPLOYEEMR_WORK_AT"
   (
    "EID" NUMBER NOT NULL ENABLE,
	"SID" NUMBER NOT NULL ENABLE,
    PRIMARY KEY ("EID", "SID"),
    FOREIGN KEY ("EID")
	  REFERENCES "ZZHA"."EMPLOYEEMR" ("EID") ENABLE,
    FOREIGN KEY ("SID")
	  REFERENCES "ZZHA"."SERVICE_CENTER" ("SID") ENABLE
    );

CREATE TABLE "ZZHA"."MECHANIC_WORK_AT"
   (
    "EID" NUMBER NOT NULL ENABLE,
	"SID" NUMBER NOT NULL ENABLE,
    PRIMARY KEY ("EID", "SID"),
    FOREIGN KEY ("EID")
	  REFERENCES "ZZHA"."MECHANIC" ("EID") ENABLE,
    FOREIGN KEY ("SID")
	  REFERENCES "ZZHA"."SERVICE_CENTER" ("SID") ENABLE
    );

CREATE TABLE "ZZHA"."CUSTOMER"
   (
	"CID" NUMBER NOT NULL ENABLE,
    "EMAIL" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(64 BYTE) NOT NULL ENABLE,
    "NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"PHONE" VARCHAR2(20 BYTE),
    PRIMARY KEY ("CID")
    );

CREATE TABLE "ZZHA"."CUSTOMER_AT_CENTER"
   (
    "CID" NUMBER NOT NULL ENABLE,
	"SID" NUMBER NOT NULL ENABLE,
    PRIMARY KEY ("CID", "SID"),
    FOREIGN KEY ("CID")
	  REFERENCES "ZZHA"."CUSTOMER" ("CID") ENABLE,
    FOREIGN KEY ("SID")
	  REFERENCES "ZZHA"."SERVICE_CENTER" ("SID") ENABLE
    );

CREATE TABLE "ZZHA"."CAR_MODEL"
   (
   	"CMID" NUMBER NOT NULL ENABLE,
	"MAKE" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"MODEL" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"YEAR" NUMBER,
	 PRIMARY KEY ("CMID")
   );

CREATE TABLE "ZZHA"."VEHICLE"
   (
    "LICENCE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"YEAR" NUMBER,
	"MILEAGE" NUMBER,
	"SERVICE_TYPE" VARCHAR2(200 BYTE),
	"SERVICE_DATE" DATE,
    "PURCHASE_DATE" DATE,
    "CMID" NUMBER NOT NULL ENABLE,
    PRIMARY KEY ("LICENCE_ID"),
    FOREIGN KEY ("CMID")
	  REFERENCES "ZZHA"."CAR_MODEL" ("CMID") ENABLE
    );

CREATE TABLE "ZZHA"."OWN"
   (
    "CID" NUMBER NOT NULL ENABLE,
	"LICENCE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PRIMARY KEY ("CID", "LICENCE_ID"),
    FOREIGN KEY ("LICENCE_ID")
	  REFERENCES "ZZHA"."VEHICLE" ("LICENCE_ID") ENABLE,
    FOREIGN KEY ("CID")
	  REFERENCES "ZZHA"."CUSTOMER" ("CID") ENABLE
    );

CREATE TABLE "ZZHA"."PART"
   (
    "PID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"MAKE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"PRICE" NUMBER NOT NULL ENABLE,
	"WARRANTY" NUMBER,
    PRIMARY KEY ("PID")
    );

CREATE TABLE "ZZHA"."INVENTORY"
   (
    "PID" NUMBER NOT NULL ENABLE,
	"SID" NUMBER NOT NULL ENABLE,
    "THRESHOLD" NUMBER DEFAULT 0 NOT NULL ENABLE,
    "QUANTITY" NUMBER DEFAULT 0 NOT NULL ENABLE,
    "MINIMAL_ORDER" NUMBER DEFAULT 0 NOT NULL ENABLE,
    PRIMARY KEY ("PID", "SID"),
    FOREIGN KEY ("PID")
	  REFERENCES "ZZHA"."PART" ("PID") ENABLE,
    FOREIGN KEY ("SID")
	  REFERENCES "ZZHA"."SERVICE_CENTER" ("SID") ENABLE
    );

CREATE TABLE "ZZHA"."DISTRIBUTOR_DELIVERY"
   (
    "PID" NUMBER NOT NULL ENABLE,
	"DID" NUMBER NOT NULL ENABLE,
    "DAYS" NUMBER NOT NULL ENABLE,
    PRIMARY KEY ("PID", "DID"),
    FOREIGN KEY ("PID")
	  REFERENCES "ZZHA"."PART" ("PID") ENABLE,
    FOREIGN KEY ("DID")
	  REFERENCES "ZZHA"."DISTRIBUTOR" ("DID") ENABLE
    );

CREATE TABLE "ZZHA"."ORDER_FROM_SERVICE_CENTER"
   (
    "SSID" NUMBER NOT NULL ENABLE,
	"SOID" NUMBER NOT NULL ENABLE,
	"QUANTITY" NUMBER,
	"PID" NUMBER NOT NULL ENABLE,
	"ORDER_DATE" DATE,
	"STATUS" VARCHAR2(20 BYTE),
	"BSID" NUMBER NOT NULL ENABLE,
    "EXPECTED_DELIVERY_DATE" DATE,
    "ACTUAL_DELIVERY_DATE" DATE,
    PRIMARY KEY ("SOID"),
    FOREIGN KEY ("SSID")
	  REFERENCES "ZZHA"."SERVICE_CENTER" ("SID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("PID")
	  REFERENCES "ZZHA"."PART" ("PID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("BSID")
	  REFERENCES "ZZHA"."SERVICE_CENTER" ("SID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "ZZHA"."ORDER_FROM_DISTRIBUTOR"
   (
    "SDID" NUMBER NOT NULL ENABLE,
	"DOID" NUMBER NOT NULL ENABLE,
	"QUANTITY" NUMBER,
	"PID" NUMBER NOT NULL ENABLE,
	"DATETIME" DATE,
	"STATUS" VARCHAR2(20 BYTE),
	"BSID" NUMBER NOT NULL ENABLE,
    "EXPECTED_DELIVERY_DATE" DATE,
    "ACTUAL_DELIVERY_DATE" DATE,
    PRIMARY KEY ("DOID"),
    FOREIGN KEY ("PID")
	  REFERENCES "ZZHA"."PART" ("PID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("SDID")
	  REFERENCES "ZZHA"."DISTRIBUTOR" ("DID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("BSID")
	  REFERENCES "ZZHA"."SERVICE_CENTER" ("SID") ON DELETE CASCADE ENABLE
    );

CREATE TABLE "ZZHA"."BASIC_SERVICE"
   (
    "BSID" NUMBER NOT NULL,
    "NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"TIME" NUMBER,
	"CHARGERATE" NUMBER,
     PRIMARY KEY ("BSID")
    );


CREATE TABLE "ZZHA"."BASIC_SERVICE_NEED"
   (
    "BSID" NUMBER NOT NULL ENABLE,
    "CMID" NUMBER NOT NULL ENABLE,
	"PID" NUMBER NOT NULL ENABLE,
	"QUANTITY" NUMBER,
    PRIMARY KEY ("PID","BSID", "CMID"),
    FOREIGN KEY ("PID")
	  REFERENCES "ZZHA"."PART" ("PID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("BSID")
	  REFERENCES "ZZHA"."BASIC_SERVICE" ("BSID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("CMID")
      REFERENCES "ZZHA"."CAR_MODEL" ("CMID") ON DELETE CASCADE ENABLE
    );


CREATE TABLE "ZZHA"."MAINTENANCE_SERVICE"
   (
   	"SVID" NUMBER NOT NULL ENABLE,
	"SERVICE_TYPE" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"CAR_MODEL" NUMBER NOT NULL ENABLE,
	"MILE" NUMBER NOT NULL ENABLE,
	 PRIMARY KEY ("SVID"),
	 FOREIGN KEY ("CAR_MODEL")
	  REFERENCES "ZZHA"."CAR_MODEL" ("CMID") ENABLE
   );


CREATE TABLE "ZZHA"."MAINTENANCE_INCLUDE"
   (	
    "SVID" NUMBER NOT NULL ENABLE,
	"BSID" NUMBER NOT NULL ENABLE,
	 PRIMARY KEY ("SVID", "BSID"),
	 FOREIGN KEY ("BSID")
	  REFERENCES "ZZHA"."BASIC_SERVICE" ("BSID") ON DELETE CASCADE ENABLE
   );

 CREATE TABLE "ZZHA"."REPAIR_SERVICE"
   (	
    "RSVID" NUMBER NOT NULL ENABLE,
	"SPECIFIC_PROBLEM" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"REPORT" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	"DIAGNOSTIC_FEE" NUMBER DEFAULT 0 NOT NULL ENABLE,
	 PRIMARY KEY ("RSVID")
   );

 CREATE TABLE "ZZHA"."REPAIR_INCLUDE"
   (	"RSVID" NUMBER NOT NULL ENABLE,
	"BSID" NUMBER NOT NULL ENABLE,
	 PRIMARY KEY ("RSVID", "BSID"),
 	FOREIGN KEY ("RSVID")
	  REFERENCES "ZZHA"."REPAIR_SERVICE" ("RSVID") ON DELETE CASCADE ENABLE,
	FOREIGN KEY ("BSID")
	  REFERENCES "ZZHA"."BASIC_SERVICE" ("BSID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "ZZHA"."SCHEDULE_SERVICE"
   (
    "AID" NUMBER NOT NULL ENABLE,
    "SERVICE_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "SVID" NUMBER,
    "RSVID" NUMBER,
	"SID" NUMBER NOT NULL ENABLE,
	"CID" NUMBER NOT NULL ENABLE,
	"LICENCE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"EID" NUMBER NOT NULL ENABLE,
	"SERVICE_DATE" TIMESTAMP,
    "SERVICE_END_DATE" TIMESTAMP,
    PRIMARY KEY ("AID"),
    FOREIGN KEY ("SID")
	  REFERENCES "ZZHA"."SERVICE_CENTER" ("SID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("CID")
	  REFERENCES "ZZHA"."CUSTOMER" ("CID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("EID")
	  REFERENCES "ZZHA"."MECHANIC" ("EID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("LICENCE_ID")
	  REFERENCES "ZZHA"."VEHICLE" ("LICENCE_ID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("SVID")
      REFERENCES "ZZHA"."MAINTENANCE_SERVICE" ("SVID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("RSVID")
      REFERENCES "ZZHA"."REPAIR_SERVICE" ("RSVID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "ZZHA"."NOTIFICATION"
   (
    "NID" NUMBER NOT NULL ENABLE,
	"NOTIFY_TIME" TIMESTAMP NOT NULL ENABLE,
	"DOID" NUMBER,
    "SOID" NUMBER,
	"DELAYED_BY" NUMBER,
     PRIMARY KEY ("NID"),
    FOREIGN KEY ("DOID")
	  REFERENCES "ZZHA"."ORDER_FROM_DISTRIBUTOR" ("DOID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("SOID")
      REFERENCES "ZZHA"."ORDER_FROM_SERVICE_CENTER" ("SOID") ON DELETE CASCADE ENABLE
    );


CREATE TABLE "ZZHA"."INVOICE"
    (
     "IID" NUMBER NOT NULL ENABLE,
     "SVID" NUMBER,
     "RSVID" NUMBER,
     "SERVICE_STRAT_DATE" TIMESTAMP,
     "SERVICE_END_DATE" TIMESTAMP,
     "LICENCE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "SERVICE_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "MECHANIC_NAME" VARCHAR2(64 BYTE) NOT NULL ENABLE,
     "TOTAL_SERVICE_COST" NUMBER,
      PRIMARY KEY ("IID"),
     FOREIGN KEY ("LICENCE_ID")
	  REFERENCES "ZZHA"."VEHICLE" ("LICENCE_ID") ON DELETE CASCADE ENABLE,
     FOREIGN KEY ("SVID")
      REFERENCES "ZZHA"."MAINTENANCE_SERVICE" ("SVID") ON DELETE CASCADE ENABLE,
     FOREIGN KEY ("RSVID")
      REFERENCES "ZZHA"."REPAIR_SERVICE" ("RSVID") ON DELETE CASCADE ENABLE
    );

CREATE SEQUENCE  "ZZHA"."EMPLOYEE_SEQUENCE"
MINVALUE 1 MAXVALUE 10000000000
INCREMENT BY 1 START WITH 950932131 CACHE 20
ORDER  NOCYCLE ;

CREATE SEQUENCE  "ZZHA"."CUSTOMER_SEQUENCE"
MINVALUE 1 MAXVALUE 1000000000
INCREMENT BY 1 START WITH 1005 CACHE 20
ORDER  NOCYCLE ;

CREATE SEQUENCE  "ZZHA"."SVERVICE_CENTER_SEQUENCE"
MINVALUE 1 MAXVALUE 10000000000
INCREMENT BY 1 START WITH 3 CACHE 20
ORDER  NOCYCLE ;

CREATE SEQUENCE  "ZZHA"."PART_SEQUENCE"
MINVALUE 1 MAXVALUE 1000000000
INCREMENT BY 1 START WITH 52 CACHE 20
ORDER  NOCYCLE ;

CREATE SEQUENCE  "ZZHA"."ORDER_SEQUENCE"
MINVALUE 1 MAXVALUE 10000000000
INCREMENT BY 1 START WITH 9 CACHE 20
ORDER  NOCYCLE ;

CREATE SEQUENCE  "ZZHA"."SCHEDULE_SEQUENCE"
MINVALUE 1 MAXVALUE 1000000000
INCREMENT BY 1 START WITH 17 CACHE 20
ORDER  NOCYCLE ;

CREATE SEQUENCE  "ZZHA"."NOTIFICATION_SEQUENCE"
MINVALUE 1 MAXVALUE 1000000000
INCREMENT BY 1 START WITH 4 CACHE 20
ORDER  NOCYCLE ;

CREATE SEQUENCE  "ZZHA"."CAR_MODEL_SEQUENCE"
MINVALUE 1 MAXVALUE 1000000000
INCREMENT BY 1 START WITH 7 CACHE 20
ORDER  NOCYCLE ;

CREATE SEQUENCE  "ZZHA"."SERVICE_SEQUENCE"
MINVALUE 1 MAXVALUE 1000000000
INCREMENT BY 1 START WITH 27 CACHE 20
ORDER  NOCYCLE ;
